version: "3"

networks:
  app:
    driver: bridge
  web:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: kk-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # If you want to save your data into host, uncomment this.
      # BUT, files will saved as root, it's not preventable.
      # - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kk-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ABSOLUTE_URI=http://${HOST}/phpmyadmin/
    depends_on:
      - mysql
    networks:
      - app
      - web
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  front-end:
    build: ./front-end
    container_name: kk-front-end
    environment:
      - ENVIRONMENT=dev
      - HOST=${HOST}
      - schema=https
    networks:
      - web
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CODE_PATH_FRONTEND}:/home/node/app

  back-end:
    build:
      context: ./back-end
    container_name: kk-back-end
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=debug
      - HOST=${HOST}
    depends_on:
      - mysql
    networks:
      - app
      - web
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CODE_PATH_BACKEND}:/home/node/app

  nginx:
    image: nginx:latest
    container_name: kk-nginx
    environment: 
      - HOST=${HOST}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - front-end
      - back-end
    networks:
      - web
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/templates/default-ssl.conf:/etc/nginx/templates/default-ssl.conf.template
      - ./nginx/templates/development-ssl.conf:/etc/nginx/templates/development-ssl.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
