version: "3"

networks:
  app:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: kk-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # If you want to save your data into host, uncomment this.
      # BUT, files will saved as root, it's not preventable.
      # - ./data/mysql:/var/lib/mysql

  front-end:
    build: ./front-end
    container_name: kk-front-end
    environment:
      - ENVIRONMENT=prod
      - HOST=${HOST}
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CODE_PATH_FRONTEND}:/home/node/app

  back-end:
    build:
      context: ./back-end
    container_name: kk-back-end
    environment:
      - ENVIRONMENT=prod
      - DOMAIN=${HOST}
    depends_on:
      - mysql
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${CODE_PATH_BACKEND}:/home/node/app

  nginx:
    image: nginx:latest
    container_name: kk-nginx
    environment: 
      - HOST=${HOST}
    ports:
      - 80:80
    depends_on:
      - front-end
      - back-end
    networks:
      - app
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/templates/default.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/templates/production.conf:/etc/nginx/templates/production.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
